#!/bin/bash
#$ -N BLAT_proteins
#$ -M kaitlin.gallagher@uconn.edu
#$ -m bea
#$ -S /bin/bash
#$ -cwd
#$ -pe smp 8
#$ -o KJHRD_BLAT_proteins_$JOB_ID.out
#$ -e KJHRD_BLAT_proteins_$JOB_ID.err

module load Blat
blat KJHRD_SPAdes_assembly_scaffolds.fasta tapeworm_proteins.fa KJHRD_out_blat -t=dnax -q=prot
blat KJHRE_genome.ctg.fasta tapeworm_proteins.fa KJHRE_out_blat_proteins -t=dnax -q=prot
blat KJHRF_genome.ctg.fasta tapeworm_proteins.fa KJHRF_out_blat_proteins -t=dnax -q=prot
