#!/bin/bash
#$ -N KJHRD_BLAT_EST     
#$ -M kaitlin.gallagher@uconn.edu
#$ -m bea
#$ -S /bin/bash
#$ -cwd
#$ -pe smp 8
#$ -o KJHRD_BLAT_EST_$JOB_ID.out
#$ -e KJHRD_BLAT_EST_$JOB_ID.err

module load Blat
blat KJHRD_SPAdes_assembly_scaffolds.fasta mRNA.fa KJHRD_est_out_blat -t=dnax -q=dna
blat KJHRF_genome.ctg.fasta EST.fa KJHRF_est_out_blat -t=dna -q=dna
blat KJHRE_genome.ctg.fasta EST.fa KJHRE_est_out_blat -t=dna -q=dna
