#!/bin/bash
#$ -N BLAT_proteins
#$ -M kaitlin.gallagher@uconn.edu
#$ -m bea
#$ -S /bin/bash
#$ -cwd
#$ -pe smp 8
#$ -o $JOB_NAME_$JOB_ID.out
#$ -e $JOB_NAME_$JOB_ID.err

module load Blat
blat KJHRD_SPAdes_SSPACE_assembly.fasta Platy__proteins.fasta KJHRD_out_blat -t=dnax -q=prot
blat KJHRE_masurca_SSPACE_assembly.fasta Platy_proteins.fasta KJHRD_out_blat -t=dnax -q=prot
blat KJHRF_genome.ctg.fasta tapeworm_proteins.fa KJHRF_out_blat_proteins -t=dnax -q=prot
