#!/bin/bash
#$ -N Exonerate_Proteins
#$ -M kaitlin.gallagher@uconn.edu
#$ -m bea
#$ -S /bin/bash
#$ -cwd
#$ -q highmem.q
#$ -pe smp 1
#$ -o $JOB_NAME_$JOB_ID.out
#$ -e $JOB_NAME_$JOB_ID.err

module load exonerate

exonerate --model protein2genome -t KJHRD_SPAdes_SSPACE_assembly.fasta -q Filtered_proteins_KJHRD.fasta --bestn 1 --percent 70 -s 100 --forcegtag --showtargetgff > KJHRD_Proteins_exonerate
exonerate --model protein2genome -t KJHRE_masurca_SSPACE_assembly.fasta -q Filtered_proteins_KJHRE.fasta --bestn 1 --percent 70 -s 100 --forcegtag --showtargetgff > KJHRE_Proteins_exonerate
exonerate -t /tempdata3/KGalla/amplifica/exonerate/KJHRF_genome.ctg.fasta -q /tempdata3/KGalla/amplifica/exonerate/Proteins/KJHRF_Proteins_Filtered_Seq.fasta --bestn 1 --percent 70 -s 100 --showtargetgff > KJHRF_Proteins_exonerate
