#!/bin/bash
#$ -N Exonerate_Proteins
#$ -M kaitlin.gallagher@uconn.edu
#$ -m bea
#$ -S /bin/bash
#$ -cwd
#$ -q highmem.q
#$ -pe smp 1
#$ -o $JOB_NAME_$JOB_ID.out
#$ -e $JOB_NAME_$JOB_ID.err

module load exonerate

exonerate -t /tempdata3/KGalla/aenig/exonerate/KJHRD_SPAdes_assembly_scaffolds.fasta -q /tempdata3/KGalla/aenig/exonerate/Proteins/Filtered_Seq2.fasta --bestn 1 --percent 70 -s 100 --showtargetgff > KJHRD_Proteins_exonerate
exonerate -t /tempdata3/KGalla/daileyi/exonerate/Proteins/KJHRE_genome.ctg.fasta -q /tempdata3/KGalla/daileyi/exonerate/Proteins/KJHRE_Proteins_Filtered_Seq.fasta --bestn 1 --percent 70 -s 100 --showtargetgff > KJHRE_Proteins_exonerate
exonerate -t /tempdata3/KGalla/amplifica/exonerate/KJHRF_genome.ctg.fasta -q /tempdata3/KGalla/amplifica/exonerate/Proteins/KJHRF_Proteins_Filtered_Seq.fasta --bestn 1 --percent 70 -s 100 --showtargetgff > KJHRF_Proteins_exonerate
