#!/usr/bin/env python

import sys,re

VulgLines=[]
with open("KJHRF_Proteins_exonerate") as f:
        for line in f:
                if line[0] == "v":
                        VulgLines.append(line)
ID=[]
for i in VulgLines:
        column=i.split(" ")
        ID.append(column[1])

UniqSeq=set(ID)
print (len(UniqSeq))
