#!/usr/bin/env python

import sys,re
SeqNames=[]
with open("KJHRD_out_blat2") as f:
        for line in f:
                SeqNames.append(line.split()[9])

UniqNames=set(SeqNames)
print (UniqNames)
print (len(UniqNames))

Names=list(UniqNames)
NamePerLine='\n'.join([ str(myelement) for myelement in Names ]) ##adds line delimiters so each name gets its own line
print(NamePerLine)

fh=open("UniqueGeneNames.txt", "w")
fh.writelines(NamePerLine)
fh.close()
