#!/usr/bin/env python

import sys,re
from Bio import SeqIO

VulgLines=[]
with open("KJHRD_Proteins_exonerate") as f:
        for line in f:
                if line[0] == "v":
                        VulgLines.append(line)
ID=[]
for i in VulgLines:
        column=i.split(" ")
        ID.append(column[1])

UniqSeq=set(ID)
print (len(UniqSeq))
Names=list(UniqSeq)

NamePerLine='\n'.join([ str(myelement) for myelement in Names ])
print(NamePerLine)

fh=open("KJHRD_Prot_Exonerate_UniqueGenes.txt", "w")
fh.writelines(NamePerLine)
fh.close()

output = open("KJHRD_Filtered_Exonerate_ProtSeq.fasta", "w")

wanted = set(line.rstrip("\n").split(None,1)[0] for line in open("KJHRD_Prot_Exonerate_UniqueGenes.txt","r"))

records = (r for r in SeqIO.parse(open("Filtered_Seq2.fasta", "r"),'fasta') if r.id in wanted)

SeqIO.write(records, output, "fasta")

output.close()
